### ISSUE TITLE
Implement location page

### ISSUE THREAD

**Issue by sonalranjit** [bikespace/bikespace#10]
<img width="378" alt="Screen Shot 2023-03-28 at 8 49 47 PM" src="https://user-images.githubusercontent.com/12193813/228398432-2edd6c9b-8454-464c-a6e4-f2bf8a449b55.png">

**Comment by kevinluo201** [comment]
@sonalranjit Do I need to be one of the developers of this project to be assigned to the issues? 😃

**Comment by sonalranjit** [comment]
Im not sure but i was able to just now. Maybe have to be a maintainer? I can change that for you

**Comment by kevinluo201** [comment]
ok, add me as a maintainer 😉

**Comment by sonalranjit** [comment]
Ive sent the invitation
