### ISSUE TITLE
Add dashboard layout into app

### ISSUE THREAD

**Issue by hulloanson** [bikespace/bikespace#133]
Part of the merging dashboard into react app effort

Move what we have here:

![image](https://github.com/bikespace/bikespace/assets/9977536/f520703a-f9a3-438b-9bd2-59de4d76c3bc)

into the `bikespace_frontend` project

**Comment by hulloanson** [comment]
the new app for now will live in the `develop` branch. This feature will branch off from it.

**Comment by xinweny** [comment]
I'll be happy to work on it.

**Comment by tallcoleman** [comment]
@hulloanson it looks like the existing `develop` branch is way behind `main`, should we use another branch or catch up `develop`?

**Comment by hulloanson** [comment]
let's catch up develop. it should be a fast-forward?

**Comment by hulloanson** [comment]
it was a fast-forward indeed. did just that

**Comment by hulloanson** [comment]
`develop` should diverge as we add dashboard features into it though. We may not merge from `main` when it happens.

**Comment by tallcoleman** [comment]
@xinweny the .gitignore excludes any folder named "data" so when I pull from the development branch and try to run, I get import errors for where you've put api-data attributes. Can you rename that folder and commit it to develop?

```bash
src/components/dashboard/map-marker/MapMarker.tsx:8:29 - error TS2307: Cannot find module '@/data/api-data-attributes' or its corresponding type declarations.

8 import {issuePriority} from '@/data/api-data-attributes';
                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/components/dashboard/map-popup/MapPopup.tsx:6:29 - error TS2307: Cannot find module '@/data/api-data-attributes' or its corresponding type declarations.

6 import {issuePriority} from '@/data/api-data-attributes';
```

**Comment by xinweny** [comment]
Oops sorry I didn't notice! I've just renamed it to `utils`.

**Comment by tallcoleman** [comment]
Works now - thanks @xinweny !
