### ISSUE TITLE
Add profanity censor package to filter incoming comments

### ISSUE THREAD

**Issue by sonalranjit** [bikespace/bikespace#24]
add https://github.com/snguyenthanh/better_profanity to sanitize incoming comments for profanity

**Comment by kevinluo201** [comment]
Do people really leave that kind of comment? 😆 🤯 People in Toronto live in stressful lives...

**Comment by sonalranjit** [comment]
Haha not really, but i was parsing some old data and saw some that had some profanity. Doesnt cost much to censor it so just thought to add it.
