### ISSUE TITLE
Change 'back' button text to 'close'

### ISSUE THREAD

**Issue by whoisasey** [bikespace/bikespace#30]
Upon form submission, the 'back' text should say 'Close' to better help the user understand that the flow is finished.
The user could think that click 'back' will bring them backwards through the form, but if the intent is to bring them back to the home page like it is currently, it should be more clear that they are Closing and going back Home

![Image](https://github.com/bikespace/bikespace-v2/assets/56001902/77c0c9c7-1983-47da-bdc4-2fb86d86c34c)

**Comment by harsha-mangena** [comment]
@whoisasey 
Seems like a direct change Please find the below PR:https://github.com/bikespace/bikespace-v2/pull/48
Thanks in advance!!
