### ISSUE TITLE
Set default limit on submissions endpoint when getting submissions

### ISSUE THREAD

**Issue by sonalranjit** [bikespace/bikespace#33]
currently `/submissions` endpoint returns everything from the database when queried. Ideally, following the API spec, there should be a default limit on number of items on a page.

**Comment by harsha-mangena** [comment]
@sonalranjit, Can I work on this?

**Comment by sonalranjit** [comment]
@harsha-mangena sure! Would you minding forking the repo and submitting a PR from your fork.
Please ask any questions you might have on this.

**Comment by harsha-mangena** [comment]
@sonalranjit , Sure thing
