### ISSUE TITLE
Allow longer text for comments box and indicator of text limit in comments box

### ISSUE THREAD

**Issue by sonalranjit** [bikespace/bikespace#81]
Seems the postgres comments field is set to 256 long only. Update the postgres column to accept longer text.
Also the comment text box could display the character limit of the text box so the user is informed about their text size.

**Comment by HimanshuDTU18** [comment]
assign this to me please

**Comment by Ydixit007** [comment]
I can add an indicator in comments.tsx to display the text limit in the bottom right of the text area. Will add other basic functionality  like not accepting more characters than the imposed limit.

**Comment by hulloanson** [comment]
we also need to make sure longer comments display correctly on the dashboard
