### ISSUE TITLE
Set the marker colors to correspond to the colors for the issue type

### ISSUE THREAD

**Issue by sonalranjit** [bikespace/bikespace#82]
Feedback from user: 
"If I can make a suggestion, not sure if possible but the colour coding for the different issues is useful – however once you get down to the individual pin, the colour dissapears. In other words once you're zoomed in to individual instances, the pins all look the same and you have to click each one to see what the issue is. Is it possible in this tool to colour code the pins themselves to match your legend?"

The default marker is the blue from leaflet. The user is asking if it'd be feasible to match the marker color to the color in the frequency chart.

![Image](https://github.com/bikespace/bikespace/assets/12193813/92c54617-c48d-4dbf-811f-d0450012b668)

**Comment by tallcoleman** [comment]
Sure, I can work on this - already had a draft issue in the kanban for "Customize map point icons depending on issue type(s) reported". The colors in the chart also aren't the same as the ones used in the pop-up issue tag styling, so I want to make those consistent as well.

Ideally we could put in custom markers as well... will see if I can use the ones from the figma or maybe we can get someone to help make them.
