### ISSUE TITLE
Update landing page

### ISSUE THREAD

**Issue by tallcoleman** [bikespace/bikespace#84]
Have started making some edits in the landingpage-updates branch. Contributions or comments about content that needs to be updated are welcome!

ToDos:

- [x] Accessibility testing
- [x] Update dashboard image
- [x] Update parking map (I've figured out the data side of this already, see: [github.com/tallcoleman/new-parking-map](https://github.com/tallcoleman/new-parking-map/tree/main/Display%20Files))
- [x] Update "why now" section
- [x] Update "get involved" section - would be good to have links to the issues page, kanban, CTTO meetup, etc.
- [x] Update contact info and social links (all currently inactive?)
- [ ] Consider changing hero image so it's less distracting from the key nav buttons (try to find something just as beautiful though...)

**Comment by sonalranjit** [comment]
@tallcoleman I have a PR with the changes to rename `report.html` to `index.html`, might affect the references here in your changes with dashboard URL.
https://github.com/bikespace/bikespace/pull/86
