### ISSUE TITLE
Implement Issue page

### ISSUE THREAD

**Issue by sonalranjit** [bikespace/bikespace#9]
<img width="425" alt="Screen Shot 2023-03-28 at 8 49 04 PM" src="https://user-images.githubusercontent.com/12193813/228398292-ab38cc42-0b55-4297-a068-546acea5c267.png">

**Comment by kevinluo201** [comment]
@sonalranjit 
https://github.com/kevinluo201/bikespace-v2/tree/feature/issue-page
I only adjusted styles. I was struggling to send props to Components like Issue...
![image](https://user-images.githubusercontent.com/1151907/229403177-1c77b244-c158-46c1-a126-a8f432e70e62.png)

**Comment by kevinluo201** [comment]
vanilla-extract css cannot load files. It needs another package to do that. I wanted to load the background image as the background of <main> so I chose to use `.scss`. Then I found `scss` is easier to use than vanilla-extract CSS, so I just used `.scss` after that. I think it can be translated into vanilla-extract CSS later if needed.

**Comment by sonalranjit** [comment]
ohh amazing! @kevinluo201 yeah whatever works at this point
