### ISSUE TITLE
make sure user chooses at least one issue

### ISSUE THREAD

**Issue by hulloanson** [bikespace/bikespace#95]

**Comment by hulloanson** [comment]
And maybe select "bicycle parking is not provided" as default

**Comment by hulloanson** [comment]
closed by #102

**Comment by tallcoleman** [comment]
This issue doesn't actually appear to have been fixed by #102, but is fixed now with [commit 06668b0](https://github.com/bikespace/bikespace/commit/06668b0204f72f38d948544aad756fbf7992537c) in `develop`. Can be closed again when `develop` is merged into `main`

**Comment by tallcoleman** [comment]
closed with https://github.com/bikespace/bikespace/pull/146
